# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projekte\InMoov\navManager\gui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.slaveServers = QtWidgets.QGroupBox(self.centralwidget)
        self.slaveServers.setGeometry(QtCore.QRect(30, 30, 161, 131))
        self.slaveServers.setObjectName("slaveServers")
        self.aruco = QtWidgets.QCheckBox(self.slaveServers)
        self.aruco.setGeometry(QtCore.QRect(10, 60, 70, 17))
        self.aruco.setTristate(True)
        self.aruco.setObjectName("aruco")
        self.kinect = QtWidgets.QCheckBox(self.slaveServers)
        self.kinect.setGeometry(QtCore.QRect(10, 40, 70, 17))
        self.kinect.setTristate(True)
        self.kinect.setObjectName("kinect")
        self.servoControl = QtWidgets.QCheckBox(self.slaveServers)
        self.servoControl.setGeometry(QtCore.QRect(10, 80, 85, 17))
        self.servoControl.setTristate(True)
        self.servoControl.setObjectName("servoControl")
        self.cartControl = QtWidgets.QCheckBox(self.slaveServers)
        self.cartControl.setGeometry(QtCore.QRect(10, 100, 77, 17))
        self.cartControl.setTristate(True)
        self.cartControl.setObjectName("cartControl")
        self.taskOrchestrator = QtWidgets.QCheckBox(self.slaveServers)
        self.taskOrchestrator.setGeometry(QtCore.QRect(10, 20, 105, 17))
        self.taskOrchestrator.setTristate(True)
        self.taskOrchestrator.setObjectName("taskOrchestrator")
        self.Map = QtWidgets.QLabel(self.centralwidget)
        self.Map.setGeometry(QtCore.QRect(30, 180, 300, 300))
        self.Map.setFrameShape(QtWidgets.QFrame.Box)
        self.Map.setAlignment(QtCore.Qt.AlignCenter)
        self.Map.setObjectName("Map")
        self.cartGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.cartGroup.setGeometry(QtCore.QRect(230, 30, 181, 141))
        self.cartGroup.setObjectName("cartGroup")
        self.cartDegrees = QtWidgets.QLabel(self.cartGroup)
        self.cartDegrees.setGeometry(QtCore.QRect(80, 20, 91, 16))
        self.cartDegrees.setObjectName("cartDegrees")
        self.cartLocation = QtWidgets.QLabel(self.cartGroup)
        self.cartLocation.setGeometry(QtCore.QRect(80, 40, 81, 16))
        self.cartLocation.setObjectName("cartLocation")
        self.mapLocation = QtWidgets.QLabel(self.cartGroup)
        self.mapLocation.setGeometry(QtCore.QRect(80, 60, 91, 16))
        self.mapLocation.setObjectName("mapLocation")
        self.MapLocation_4 = QtWidgets.QLabel(self.cartGroup)
        self.MapLocation_4.setGeometry(QtCore.QRect(10, 100, 70, 16))
        self.MapLocation_4.setObjectName("MapLocation_4")
        self.MapLocation_5 = QtWidgets.QLabel(self.cartGroup)
        self.MapLocation_5.setGeometry(QtCore.QRect(10, 120, 70, 16))
        self.MapLocation_5.setObjectName("MapLocation_5")
        self.laptop = QtWidgets.QLabel(self.cartGroup)
        self.laptop.setGeometry(QtCore.QRect(80, 80, 91, 16))
        self.laptop.setObjectName("laptop")
        self.v12 = QtWidgets.QLabel(self.cartGroup)
        self.v12.setGeometry(QtCore.QRect(80, 100, 71, 16))
        self.v12.setObjectName("v12")
        self.v6 = QtWidgets.QLabel(self.cartGroup)
        self.v6.setGeometry(QtCore.QRect(80, 120, 71, 16))
        self.v6.setObjectName("v6")
        self.MapLocation_2 = QtWidgets.QLabel(self.centralwidget)
        self.MapLocation_2.setGeometry(QtCore.QRect(240, 90, 70, 16))
        self.MapLocation_2.setObjectName("MapLocation_2")
        self.cartDegrees_2 = QtWidgets.QLabel(self.centralwidget)
        self.cartDegrees_2.setGeometry(QtCore.QRect(240, 50, 61, 16))
        self.cartDegrees_2.setObjectName("cartDegrees_2")
        self.Location_2 = QtWidgets.QLabel(self.centralwidget)
        self.Location_2.setGeometry(QtCore.QRect(240, 70, 47, 16))
        self.Location_2.setObjectName("Location_2")
        self.showCart = QtWidgets.QCheckBox(self.centralwidget)
        self.showCart.setGeometry(QtCore.QRect(30, 490, 73, 17))
        self.showCart.setObjectName("showCart")
        self.showTarget = QtWidgets.QCheckBox(self.centralwidget)
        self.showTarget.setGeometry(QtCore.QRect(30, 520, 84, 17))
        self.showTarget.setObjectName("showTarget")
        self.showScanLocations = QtWidgets.QCheckBox(self.centralwidget)
        self.showScanLocations.setGeometry(QtCore.QRect(150, 490, 123, 17))
        self.showScanLocations.setObjectName("showScanLocations")
        self.showMarkers = QtWidgets.QCheckBox(self.centralwidget)
        self.showMarkers.setGeometry(QtCore.QRect(150, 520, 123, 17))
        self.showMarkers.setObjectName("showMarkers")
        self.showMovePath = QtWidgets.QCheckBox(self.centralwidget)
        self.showMovePath.setGeometry(QtCore.QRect(30, 550, 123, 17))
        self.showMovePath.setObjectName("showMovePath")
        self.numMovements = QtWidgets.QSpinBox(self.centralwidget)
        self.numMovements.setGeometry(QtCore.QRect(140, 550, 42, 22))
        self.numMovements.setMinimum(1)
        self.numMovements.setProperty("value", 3)
        self.numMovements.setObjectName("numMovements")
        self.MapLocation_3 = QtWidgets.QLabel(self.centralwidget)
        self.MapLocation_3.setGeometry(QtCore.QRect(240, 110, 70, 16))
        self.MapLocation_3.setObjectName("MapLocation_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Navigation Manager"))
        self.slaveServers.setTitle(_translate("MainWindow", "Slave Servers"))
        self.aruco.setText(_translate("MainWindow", "aruco"))
        self.kinect.setText(_translate("MainWindow", "kinect"))
        self.servoControl.setText(_translate("MainWindow", "servoControl"))
        self.cartControl.setText(_translate("MainWindow", "cartControl"))
        self.taskOrchestrator.setText(_translate("MainWindow", "taskOrchestrator"))
        self.Map.setText(_translate("MainWindow", "Map"))
        self.cartGroup.setTitle(_translate("MainWindow", "Cart"))
        self.cartDegrees.setText(_translate("MainWindow", "Degrees"))
        self.cartLocation.setText(_translate("MainWindow", "Location"))
        self.mapLocation.setText(_translate("MainWindow", "Map Location"))
        self.MapLocation_4.setText(_translate("MainWindow", "12 V:"))
        self.MapLocation_5.setText(_translate("MainWindow", "6 V:"))
        self.laptop.setText(_translate("MainWindow", "Laptop"))
        self.v12.setText(_translate("MainWindow", "12 V"))
        self.v6.setText(_translate("MainWindow", "6 V"))
        self.MapLocation_2.setText(_translate("MainWindow", "Map Location: "))
        self.cartDegrees_2.setText(_translate("MainWindow", "Degrees: "))
        self.Location_2.setText(_translate("MainWindow", "Location: "))
        self.showCart.setText(_translate("MainWindow", "Show Cart"))
        self.showTarget.setText(_translate("MainWindow", "Show Target"))
        self.showScanLocations.setText(_translate("MainWindow", "Show Scan Locations"))
        self.showMarkers.setText(_translate("MainWindow", "Show Markers"))
        self.showMovePath.setText(_translate("MainWindow", "Show Move Path"))
        self.MapLocation_3.setText(_translate("MainWindow", "Laptop:"))

